#theme: jekyll-theme-console

plugins:
  - jekyll-seo-tag

header_pages:
  - index.md
  - portfolio.md
  - project.md

style: dark # dark (default) or light

listen_for_clients_preferred_style: false # true or false (default)

markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
